stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build_and_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl gnupg lsb-release bash
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apk/keys/docker.gpg
    - docker info
  script:
    - echo "$CONFIG" | base64 -d > config.py
    - docker compose version
    - docker compose up --build -d
    - |
      for i in $(seq 1 11); do
        if ! docker ps --filter "name=mirror-leech-bot" --format '{{.Names}}' | grep -q mirror-leech-bot; then
          echo "Container exited; failing job."
          exit 1
        fi
        echo "$(date): Build is still building..."
        sleep 1800
      done
      sleep 290
      echo "$(date): Bulding finished!"
  only:
    - main  # Change this to your branch name
  when: manual  # Equivalent to `workflow_dispatch`