stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update && apt-get install -y curl gnupg lsb-release
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl start docker || true

build_and_push:
  stage: build
  script:
    - echo "$CONFIG" > config.py
    - docker compose up --build -d
    - |
      for i in {1..10}; do
        if ! docker ps --filter "name=mirror-leech-bot" --format '{{.Names}}' | grep -q mirror-leech-bot; then
          echo "Container exited; failing job."
          exit 1
        fi
        echo "$(date): Build is still building..."
        sleep 300
      done
  only:
    - master
    - schedules
    - web  # For manual trigger


