name: Build and Push image to DockerHub

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
            sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          sudo apt-get update
          sudo apt-get install -y \
            docker-ce \
            docker-ce-cli \
            containerd.io \
            docker-buildx-plugin \
            docker-compose-plugin

          sudo systemctl start docker

      - name: Assure Docker is the latest version
        run: docker compose version

      - name: Build Dcoker Image
        run: |
          git clone ${{ secrets.REPO_LINK }} cdmaoinmci
          cd cdmaoinmci
          cat <<EOF > config.py
          ${{ secrets.CONFIG }}
          EOF
          sudo docker compose up --build -d

      - name: Push Image to DockerHub
        run: |
          for i in {1..10}; do
            if ! docker ps --filter "name=mirror-leech-bot" --format '{{.Names}}' | grep -q mirror-leech-bot; then
              echo "::error ::Container exited; failing job."
              exit 1
            fi
            echo "$(date): Build is still building..."
            sleep 300
          done
